services:
    app.admin.post:
        class: AppBundle\Admin\CurrencyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Sistema", label: "Monedas" }
        arguments:
            - ~
            - AppBundle\Entity\Currency
            - ~
